### ISSUE TITLE
Manual lanes are missing

### ISSUE THREAD

**Issue by akurdyukov** [overbaard/overbaard#119]
I have board config that never shows 'Manual swimlanes'. Please see

```
{
  "name": "XXX Features",
  "code": "XXX",
  "states": [
    {
      "name": "Backlog",
      "backlog": true
    },
    {
      "name": "Selected for Development"
    },
    {
      "name": "In Progress",
      "header": "Development"
    },
    {
      "name": "Dev Finished",
      "header": "Development"
    },
    {
      "name": "Testing"
    },
    {
      "name": "Ready for Release"
    },
    {
      "name": "Released"
    },
    {
      "name": "Done",
      "done": true
    }
  ],
  "priorities": [
    {
      "name": "Blocker",
      "colour": "red"
    },
    {
      "name": "Critical",
      "colour": "darkred"
    },
    {
      "name": "Major",
      "colour": "orange"
    },
    {
      "name": "Minor",
      "colour": "greenyellow"
    },
    {
      "name": "Trivial",
      "colour": "green"
    }
  ],
  "issue-types": [
    {
      "name": "Task",
      "colour": "blue"
    },
    {
      "name": "Test",
      "colour": "blue"
    },
    {
      "name": "Story",
      "colour": "green"
    },
    {
      "name": "New Feature",
      "colour": "green"
    },
    {
      "name": "Improvement",
      "colour": "green"
    },
    {
      "name": "Bug",
      "colour": "red"
    },
    {
      "name": "Epic",
      "colour": "purple"
    }
  ],
  "manual-swimlanes": [
    {
      "name": "Manual Swimlane",
      "entries" : [
        {
          "name": "Expedite",
          "issue-ql": "priority = 'Blocker' AND status != 'Closed'"
        },
        {
          "name": "Impediment",
          "issue-ql": "Flagged = 'Impediment' AND priority != 'Blocker' AND status != 'Closed'"
        }
      ]
    }
  ],
  "projects": [
    {
      "code": "XXX",
      "query-filter": null,
      "colour": "#4667CA",
      "state-links": {
        "Backlog": "Backlog",
        "Open": "Selected for Development",
        "In Progress": "In Progress",
        "Ready for testing": "Dev Finished",
        "IN TESTING": "Testing",
        "Ready for Release": "Ready for Release",
        "Released": "Released",
        "Closed": "Done"
      }
    }
  ],
  "linked-projects": {}
}
```

**Comment by kabir** [comment]
I believe that is due to your second query not being correct.

In `Flagged = 'Impediment'`, 'Flagged' is not a valid thing to query for. I
think (am afk) there might be something output to the browser console when
you load up a board with bad manual swimlane queries.

On Monday, 14 October 2019, Alik Kurdyukov <notifications@github.com> wrote:
> I have board config that never shows 'Manual swimlanes'. Please see
>
> {
> "name": "XXX Features",
> "code": "XXX",
> "states": [
> {
> "name": "Backlog",
> "backlog": true
> },
> {
> "name": "Selected for Development"
> },
> {
> "name": "In Progress",
> "header": "Development"
> },
> {
> "name": "Dev Finished",
> "header": "Development"
> },
> {
> "name": "Testing"
> },
> {
> "name": "Ready for Release"
> },
> {
> "name": "Released"
> },
> {
> "name": "Done",
> "done": true
> }
> ],
> "priorities": [
> {
> "name": "Blocker",
> "colour": "red"
> },
> {
> "name": "Critical",
> "colour": "darkred"
> },
> {
> "name": "Major",
> "colour": "orange"
> },
> {
> "name": "Minor",
> "colour": "greenyellow"
> },
> {
> "name": "Trivial",
> "colour": "green"
> }
> ],
> "issue-types": [
> {
> "name": "Task",
> "colour": "blue"
> },
> {
> "name": "Test",
> "colour": "blue"
> },
> {
> "name": "Story",
> "colour": "green"
> },
> {
> "name": "New Feature",
> "colour": "green"
> },
> {
> "name": "Improvement",
> "colour": "green"
> },
> {
> "name": "Bug",
> "colour": "red"
> },
> {
> "name": "Epic",
> "colour": "purple"
> }
> ],
> "manual-swimlanes": [
> {
> "name": "Manual Swimlane",
> "entries" : [
> {
> "name": "Expedite",
> "issue-ql": "priority = 'Blocker' AND status != 'Closed'"
> },
> {
> "name": "Impediment",
> "issue-ql": "Flagged = 'Impediment' AND priority != 'Blocker' AND status
!= 'Closed'"
> }
> ]
> }
> ],
> "projects": [
> {
> "code": "XXX",
> "query-filter": null,
> "colour": "#4667CA",
> "state-links": {
> "Backlog": "Backlog",
> "Open": "Selected for Development",
> "In Progress": "In Progress",
> "Ready for testing": "Dev Finished",
> "IN TESTING": "Testing",
> "Ready for Release": "Ready for Release",
> "Released": "Released",
> "Closed": "Done"
> }
> }
> ],
> "linked-projects": {}
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/uUobXlE3TM-kRo1nbmIzP2P_MEciBcF_wfqKm0Q22OwsnciwytUcaL9nVr3jfgibLFc82OWj5zXv6W5aLnfEJIE2Q8VqOt39Hg6n7_XGvCiZJ97Y71J49QADX3X8m-nswFAesdMfzqYCO4yh9or3d8YkCa7a4xDfu0-2_pWzHfagzaT_sjzKh7DfMD0OqgzoJjhNn0L0na6dfSosOT2Zvh0NfFY=s0-d-e1-ft#https://github.com/notifications/beacon/AAAMGB3662CFYS4DLA2KVUDQOSKIZA5CNFSM4JAREWT2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HRUKRXQ.gif>

**Comment by akurdyukov** [comment]
I checked the console and found error `Could not parse issue-ql: priority = 'Blocker' AND status != 'Closed'`. Query `priority = Blocker AND status != Closed` does not work either. But it's perfectly fine when I try it in a search query. How can I fix it?

**Comment by kabir** [comment]
Actually 'status' is not a valid identifier to select on and there are some other IssueQL limitations: https://overbaard.github.io/docs/issue-ql.html. Trying the same query in the search filter it reports for me that `priority = 'Blocker' AND status != 'Closed'` is not valid.

I have on my TODO list to improve things in this area (being able to select on things like custom fields, remove the need to quote the values). I didn't have status in mind, but for what you are outlining I can see that it could be useful.

**Comment by akurdyukov** [comment]
Great. I removed status field condition, now everything works. I think showing query problems in a more explicit way may help users to debug situations like this.

**Comment by kabir** [comment]
Definitely, the main problem I had is how to figure out what is wrong since I am not a parsing expert (am using pegjs for this initial attempt). But your suggestion has given me some vague ideas for when I have the cycles to look into it :)

**Comment by akurdyukov** [comment]
Maybe I can help you with the parser. Can you please show me where's it in the source code?

**Comment by kabir** [comment]
That would be fantastic! I'll dig out some links when I am at my desk again tomorrow. 

The parser is quite isolated so you don't need to understand how the whole thing works. Depending on your level of interest, once the parser is working, I can either integrate it with the rest of the code myself, or guide you in what to do to get it all working.

**Comment by kabir** [comment]
Hi @akurdyukov, 

I've refreshed my memory a bit in this area now. To prepare to work on this, please take a look at the dev guide at https://overbaard.github.io/docs/developer-guide.html.

Since this is purely front-end stuff you can ignore the Atlassian SDK and Jira parts, and just focus on the Yarn/Angular parts (I think sections 1.2 and 4.1, although it probably doesn't hurt skimming the rest).

So basically from the https://github.com/overbaard/overbaard/tree/master/webapp folder you serve the application using `ng serve` from one console window and then run `ng test --source-map` from another console (the --source-map flag gives you lines in test error traces that map to the actual typescript code). When accessing the server from `ng serve` on localhost:4200 it uses some sample data from https://github.com/overbaard/overbaard/tree/master/webapp/src/rest/overbaard/1.0 (`boards.json` is the list of boards, `boards/x.json` is pretend config, and `issues/POCx.json` is example data of what the server would return when accessing a board.

There is a readme at https://github.com/overbaard/overbaard/tree/master/webapp/src/app/common/parsers/issue-ql/pegjs which explains how to update the grammar. We use https://pegjs.org behind the scenes. Then I think the first test to focus on is https://github.com/overbaard/overbaard/blob/master/webapp/src/app/common/parsers/issue-ql/issue-ql.matcher.spec.ts. Then https://github.com/overbaard/overbaard/blob/master/webapp/src/app/common/parsers/issue-ql/issue.visitor.ts reads fields from the issue and matches the values from the parser.

`issue-ql.matcher.spec.ts` uses https://github.com/overbaard/overbaard/blob/master/webapp/src/app/model/board/data/issue/board-issue.ts to inspect. In the real world this would be the parsed (with some extra adjustment) representation of each issue entry in the what would be returned by the server (as shown in the `POCx.json` files). But for this test we just hard-code data for an issue as input to the matcher. 

If you would like to match on new fields, check with me if it is not obvious what the contents of a particular field look like. Or if you prefer https://github.com/overbaard/overbaard/blob/master/webapp/src/app/model/board/data/issue/issue.model.ts#L323 has the code that populates the BoardIssue entries from the server data.

And of course any thing you want to ask, feel free to get in touch :)

If you end up working on this, we should probably create a new issue and continue the discussion there?

**Comment by kabir** [comment]
BTW (I don't know how familiar you are with Angular), before doing the above you need to run `yarn install` from the webapp/ folder
